# #__NAME__ METODU ICIN DEME YAPILDI SADECE.!! NESNE TABANLI 2 DE ANLATIMI VAR!.
#
# if __name__ == "__main__":      #BURAYA BOYLE BIR KALIP KULLANIYORUZ MODUL2 DOSYAMIZA .!!!!
#     print("Ikinci Modulun Ismi " + __name__)        #BOYLE OLDUGU ZAMAN EGER + __NAME__ KALIBINI DIGER DOSYADA CALISTIRIRSAK BURDAKI ARTIK IKINCI MODUL ISMI MODUL2 YAZMAYACAK SADECE
#                                             #__MAIN__ YANI NEREDE CALISTIRILDIYSA O YAZACAK TEK BIR SATIR OLACAK BUNNU SEBEBI ISE
#                                         #__MAIN__ OLARAK YANI CALISTIRLAN YER OLARAK BIZ BURAYI KULLANMADIK O YUZDEN BURASI YAZDIRILMIYOR.
#                                         #YAZDIRILMAMA SEBEBI ISE PRINT KOMURUNU IF KOSULUNUN ICINDE EGER SADECE BU SAYFANIN ISMI YANI + __NAME__ I __MAIN__ ISE YAZDIR YOKSA BIR SEY YAPMA DEMEMIZ.
#                                         #EGER BURDAN CALISTIRIRSAK CALISIR VE IKINCI MADULUN ISMI __MAIN__ OLUR.!!!



#\\\\\\\\\\\\\\\\\\\\\\\!!!!!!!!!!!!!!!!! SIMDI GELELIMM BU KALIBIN ORNEK KULLANIMLARINA !!!!!!!!!!!!///////////////////////

def fonksiyon():                            #PYTHON DIREKT OLARAK BUNU CALISTIRMAYACAK CUNKU BIZ DIGER TARAFTA FONKSIYON ISIMLI FONKSIYONU CAGIRMADIK
    print("Fonksiyon calisiyor.!!")         #BURADA FONKSIYON CAGIRILINCA OLACAK SEYI YAPTIK AMA CAGIRILMADI






if __name__ == "__main__":                  #BURADA ISE SADECE MAIN OLDUGU ZAMAN FONKSIYON CAGIRILACAK VE FONKSIYONUN ICINE GIRIP FONKSIYONUN ICINDEKILERI CALISTIRACAK. YANI YAZDIRCAK.!!
    fonksiyon()                 #BAKACAK DOSYANIN ISMI MAINSE YANI DIREKT OLARAK BUNU CALISTIRIRSAK FONKSIYON FONKSIYONUNU CAGIRACAK VE BASTIRMA ISLEMINI YAPICAK AMA DEGILSE
                                #IMPORT ETSEK BILE BURDA CALISMADIGI SURECE YAPMAYACAK.!!


#YANI BIZ BURDA IF __NAME__ == __MAIN__ KALIBI KOYARAK BIZ BUNU IMPORT ETTIGIMIZ ZAMAN ICINDE CALISABILIR DURUMDA OLAN BUTUN KODLARIN ISTEMIMIZ DISINDA BUTN KODLARIN CALISMASINI ENGELLEDIK
#MESELA BURADA BISSURU FONKSIYONLARIMIZ OLSUN VE BUNLARI BIZ BASKA YERDE CALISTIRMAK ISTEMIYORUZ. SADECE DIREKT BU DOAYAYI CALISTIRDIMGIZDA BU FONKSIYONU YA DA FONKSIYONLARI CALISTIR
#AMA EGER BASKASI IMPORT EDIYORSA ISTEMEDIGMIZ HERHANGI BIR SEY CALISTIRMA DIYORUZ.!!

